trigger:
  branches:
    include: 
      - 'master'
      - 'develop'
      - 'refs/tags/*'

  paths:
    include:
      - '*'
    exclude:
      - appveyor.yml
      - Changelog.md
      - Readme.md

pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1'
  inputs:
    packageType: sdk
    version: 3.1.416

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 6.0'
  inputs:
    packageType: sdk
    version: 6.0.420

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK (json)'
  inputs:
    packageType: sdk
    useGlobalJson: true

- powershell: .\build.ps1 CI --ArtifactsDirectory '$(Build.ArtifactStagingDirectory)'
  displayName: CI-Build

- task: PublishTestResults@2
  displayName: Save test results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

#- task: PublishBuildArtifacts@1
#  displayName: Save package artifacts
#  inputs:
#    PathtoPublish: $(Build.ArtifactStagingDirectory)
#    ArtifactName: Package

#- task: NuGetCommand@2
#  displayName: Publish to internal nuget feed
#  inputs:
#    command: push
#    nuGetFeedType: internal
#    publishVstsFeed: Fluent.Ribbon